apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: geetopod-client-example-springboot
    name: geetopod-client-example-springboot
  name: geetopod-client-example-springboot
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geetopod-client-example-springboot
      name: geetopod-client-example-springboot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: geetopod-client-example-springboot
        name: geetopod-client-example-springboot
    spec:
      containers:
      - image: gcr.io/geetopod/geetopod-client-example-springboot:0.1.1
        imagePullPolicy: Always
        name: ssopod-client-example-springboot
        env:
        - name: SSO_GATEWAY_URL
          value: "http://gw.geetopod.com"
        - name: WEB_URL
          value: "http://ceg-springboot.geetopod.com"
        - name: SSO_COMPANY
          value: "geetopod-developers"
        - name: IS_DEBUG
          value: "false"
        - name: SPRING_SESSION_TIMEOUT
          value: "360000"

        ports:
        - containerPort: 8080
          protocol: TCP

        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: geetopod-client-example-springboot
  namespace: default
spec:
  ports:
  - name: geetopod-client-example-springboot-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: geetopod-client-example-springboot
    name: geetopod-client-example-springboot
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
